package cn.nukkit.network.protocol;

import cn.nukkit.network.protocol.exception.DataPacketDecodeException;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import lombok.ToString;

import java.util.List;

/**
 * Created by CreeperFace on 5.3.2017.
 */
@ToString
public class MapInfoRequestPacket extends DataPacket {

    public static final byte NETWORK_ID = ProtocolInfo.MAP_INFO_REQUEST_PACKET;
    public static final int MAX_MAP_PIXELS = 128 * 128;

    public long mapId;

    /**
     * Sends pixels that are generated by the client to the server.
     *
     * @since 1.19.20
     */
    private final List<MapPixel> pixels = new ObjectArrayList<>();

    @Override
    public byte pid() {
        return NETWORK_ID;
    }

    @Override
    public void decode() throws DataPacketDecodeException {
        mapId = this.getVarLong();

        int count = (int) this.getUnsignedVarInt();
        if(count > MAX_MAP_PIXELS) {
            throw new DataPacketDecodeException("Too many pixels!");
        }

        for (int i = 0; i < count; i++) {
            MapPixel pixel = new MapPixel();
            pixel.pixel = this.getInt();
            pixel.index = this.getLShort();
            this.pixels.add(pixel);
        }
    }

    @Override
    public void encode() {
    }

    public static class MapPixel {
        /**
         * Colour value of pixel
         */
        int pixel;
        /**
         * Pixel index in map.
         */
        int index;
    }
}
